### ISSUE TITLE
Merge with chentsulin/koa-graphql

### ISSUE THREAD

**Issue by amccloud** [demohi/koa-graphql#1]
It would be nice to merge this with https://github.com/chentsulin/koa-graphql which is a fork of the express-graphql library. Mainly so that the @chentsulin fork can have a proper npm module name instead of `koa-gql`.

**Comment by desenmeng** [comment]
I will hand over the koa-graphql NPM package name  @chentsulin  @amccloud

**Comment by desenmeng** [comment]
Done @chentsulin @amccloud

**Comment by chentsulin** [comment]
@amccloud, @demohi 
thanks to made this possible :+1:
